### ISSUE TITLE
数据导入

### ISSUE THREAD

**Issue by GaoYb923** [huyuanxin/MKGS#4]
请问网盘上下载的neo4j.dump怎么导入？导入的api在哪里

**Comment by huyuanxin** [comment]
我记得下下来是一整个数据库吧，有点久远，我忘记了。dump的话可以看看neo4j的数据备份之类的文档

**Comment by huyuanxin** [comment]
可以的话加一下我的微信:huyuanxin1999

**Comment by GaoYb923** [comment]
感谢，可以导入了！

**Comment by huyuanxin** [comment]
OK。本科毕设的数据，没怎么清洗的数据的。另外一个仓库有爬虫数据
